image: Visual Studio 2022

install:
  - choco install gitversion.portable -y

environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

assembly_info:
  patch: false

before_build:
  - ps: dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - ps: dotnet build /p:GenerateAssemblyInfo=false --configuration release --no-restore

after_build:
  - cmd: nuget pack .nuget/EntityFrameworkCore.Seed.InMemory.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"

deploy:
  - provider: NuGet
    on:
      APPVEYOR_REPO_TAG: true
    api_key:
      secure: xZBCQxa5EcbACCkMmGWMk0KNtftKVpuLpM/nt2etlAFPOGDf06Tj7Hv2B/tuy1ys
    skip_symbols: true

artifacts:
  - path: '*.nupkg'
    name: Authfix.EntityFrameworkCore.Seed.InMemory

skip_commits:
  files:
    - src/EFCore.Seed.Postgres/
    - src/EFCore.Seed.SqlServer/
    - src/EFCore.Seed/

branches:
  only:
    - /release/
    - master