image: Visual Studio 2019

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - ps: dotnet build /p:GenerateAssemblyInfo=false --configuration release --no-restore

after_build:
  - cmd: nuget pack .nuget/EntityFrameworkCore.Seed.Postgres.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"

deploy:
  - provider: NuGet
    on:
      APPVEYOR_REPO_TAG: true
    api_key:
      secure: so9xZSjmhQVptFD7BaDSdkz/UzWkYUk+iyUayIHdLIdq2BxU+Vwr+9FtIyxLIg0+
    skip_symbols: true

artifacts:
  - path: '*.nupkg'
    name: Authfix.EntityFrameworkCore.Seed.Postgres

skip_commits:
  files:
    - src/EFCore.Seed.InMemory/
    - src/EFCore.Seed/

branches:
  only:
    - /release/
    - master