<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Authfix.EntityFrameworkCore.Seed</AssemblyName>
    <RootNamespace>Authfix.EntityFrameworkCore.Seed</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseFullSemVerForNuGet>true</UseFullSemVerForNuGet>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>Authfix.EntityFrameworkCore.Seed</PackageId>
    <Authors>Authfix</Authors>
    <Description>Seed mechanism for Entity Framework Core.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\EFCore.Seed.LicenseHeader" Link="EFCore.Seed.LicenseHeader" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <Version>9.0.4</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
  </ItemGroup>

</Project>
